### ISSUE TITLE
How to get organizations owned by a user

### ISSUE THREAD

**Issue by kodeine** [bennylope/django-organizations#108]
I'm trying to find the organizations a user is owner or admin at.
I can find admin by using `user_instance.organizations_organizationuser.filter(is_admin=True)`
can you help, how can i filter it with owner as well?

Thanks

**Comment by bennylope** [comment]
You're trying to test against two different tables, so you'll want to start the query at "top" of this relationship, the organization, rather than the "bottom", the user. That and make use of [Django's Q objects for `OR` filtering](https://docs.djangoproject.com/en/1.10/topics/db/queries/#complex-lookups-with-q-objects).

```python
Organization.objects.filter(Q( ... "your queries here"))
```
