### ISSUE TITLE
Scope of organizations

### ISSUE THREAD

**Issue by Jromero97** [bennylope/django-organizations#146]
Hi, How can i get the way to show data from all models in the admin filtered by the user logged in organization. Do you have a way to do that in your library? 

Thank's a lot for any help that you can bring to me!

**Comment by bennylope** [comment]
Do you mean how can you filter resources that are related to an organization so that only those to which the logged in user has an organizational connection to?

One of a few ways, but I'd probably start by overriding the [`ModelAdmin.get_queryset` method](https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_queryset) to filter the returned queryset by objects related to an organization for which the `request.user` is a member. If you're using a foreign key from the resource model(s) back to the organization model the queryset filtering should be fairly straightforward.
