### ISSUE TITLE
Integrating with custom organization models

### ISSUE THREAD

**Issue by gauravkulkarni96** [bennylope/django-organizations#161]
I might be missing out something from the docs; kindly help me out.
So I've created 3 custom organization models inheriting from `AbstractOrganization, AbstractOrganizationUser, and AbstractOrganizationOwner`. I like the default functionality of listing organizations at `/accounts` and the way invitation works. I wish to integrate the newly created models with the already existing functionality. How do I do that?

**Comment by bennylope** [comment]
Howdy! Thanks for your patience in my delayed reply. I think you're asking primarily about how to use your custom models with the default views (no?). Right now that's totally possible but not really dynamically, you have to just reuse the patterns, rather than the code. That's something planned for the 2.0 release (which currently updates support for invitations using a model-based invitation backend). The invitation update available in the branch [version-2-dev](https://github.com/bennylope/django-organizations/tree/version-2-dev), and it's also on PyPI as a [pre-release](https://pypi.org/project/django-organizations/#history).

**Comment by gauravkulkarni96** [comment]
Yes, exactly that. Currently, I've created custom views using the Abstract Viewsets. Is this the same thing you're saying?
Thanks
