### ISSUE TITLE
Ability to accept or decline an invitation

### ISSUE THREAD

**Issue by deviant32** [bennylope/django-organizations#178]
I need to have the ability for users to be invited, register, sign in and then accept or decline the invitation. Also existing users should have the ability to accept or decline. Is this as simple as extending the OrganizationUser and adding a boolean field to indicate whether or not the invitation has been accepted? Seems like this would be a feature that is already built in.

**Comment by bennylope** [comment]
You could achieve this by extending the `OrganizationUser` model and the invitation backend.

Also, in version 2 which is in pre-release, the default invitation system now no longer immediately links users but uses an intermediate tracking model so that it's much easier to allow users to decline first.
