### ISSUE TITLE
Associate models using multitable inheritence

### ISSUE THREAD

**Issue by shaunbrady** [bennylope/django-organizations#73]
Ben,

We are interested in using django-organizations.  Because we want to use most of the methods in Organization, we have inherited from that directly (as opposed to OrganizationBase).  We have done the same with OrganizationUser and OrganizationOwner.

When we use utils.create_organization(), I can get it to successfully create our inheriting NimbisOrganization (overriding the model in the views).  However, the relations are back to OrganizationUser and OrganizationOwner.  This makes sense, as those are the ForeignKeys in place.

I believe if I can consistently override what OrganizationUser/Owner models are used, we can keep using the FKs from the provided models.  I see here:
https://github.com/bennylope/django-organizations/blob/dev/organizations/utils.py#L52
that in the .create_organization() function the models are looked up via the FKs themselves.

I could easily write my own create_organization method, specifically using my NimbisOrganizationUser/Owner models, but I was wondering if I will run in to problems else where, if this is the only place (other than the views) I do this?

Thanks!

SB

**Comment by bennylope** [comment]
If your concern is creating instances of your custom classes, then that may be the only problem. You'll also need to concern yourself with creating users via the [invitation and registration backends](https://github.com/bennylope/django-organizations/blob/dev/organizations/backends/defaults.py) but that's something that you should really be extending (with at least minor customizations) anyhow.

This is presuming you want to make changes to the `OrganizationUser` and `OrganizationOwner` models, because otherwise you can use the default models with your own organization class (inheriting from `Organization`) just fine.

If you're doing lots of customization, to the extent that you need custom user and owner models, I'd recommend building your models from the base classes. It's going to be a much cleaner, simpler to user architecture.
