### ISSUE TITLE
Any plans for integration with django-guardian?

### ISSUE THREAD

**Issue by calvinchengx** [bennylope/django-organizations#9]

**Comment by asteinlein** [comment]
Just came across this when evaluating both django-organizations and django-guardian. They cover different use-cases indeed, but off-hand I don't see how I can make them work together nicely – please provide guidance if I'm wrong.

The end goal is having organizations with multiple users, with object-level permissions for "things" each organization creates. In django-ogranizations, that is the Organization, while in django-guadian this is a plain Django Group. In other words, I don't want users to own the "things" created, but the organization/group.

What I need to do now, AFAICS, is to create both a Group and an Organization for each organization/account in our app. It would be ideal if an Organization could extend the Django Group model, thus letting us create just a single model for each organization/account and use the object-level group permissions as supported by django-guardian.

Just browsing the code and docs a bit, I don't see a way to do this now? Again, without both an organization and a group, a concept that is IMHO tightly related.

**Comment by bennylope** [comment]
> In django-ogranizations, that is the Organization, while in django-guadian this is a plain Django Group.

It's true that Guardian provides permission tracking by `auth.Group`, but it also does so using `auth.User`. Permissions are not strictly tied to the `auth.Group`. The implementations I've seen, at least, have all used the `auth.User` level permission, for what it's worth.

However, it's better to think about *ownership* in Django Organizations. Simple implementation of *permissions* is a convenient side effect of that, but this is largely why they're not the same.

> I don't see how I can make them work together nicely

It depends on how nice you want the integration to be.

There's basically two pieces to this: (1) creating objects and their ownership/permission relations and (2) checking these relationships. For the latter I'd use my own view mixins, for example, to check against a combination of ownership (organization) and permission (Guardian permission relation). Maybe this means allowing a member of an organization to access all objects owned by that organization, irrespective of permission, while allowing other users access of some kind or another based on their permission, by user or group. That might sound complicated because it implies dual group tracks: `organization.Organization` and `auth.Group` but the key is that in general there's nothing that says group based permissions are *necessarily* predicated on *groups as organizations*; the most typical use use for `auth.Group` type groups is for *roles*.

A step beyond this would be [to create your own models from the base models](http://django-organizations.readthedocs.org/en/latest/cookbook.html#advanced-customization) and use Django Guardians' base models to create an organization-centric group permission of your own.

I'd stress again that I think this is ultimately an architectural design decision first, library decision second. In a multi-tenant situation you're going to want some kind of ownership tracking. Relying on implicit ownership through many-to-many relations isn't something I'd feel comfortable doing, myself.

> It would be ideal if an Organization could extend the Django Group model

Solely for the sake of going on the record about this, I don't think this would be ideal. You might be able to make it work but again, these are two very different things. I looked at using `auth.Group` for this purpose when starting the project, and while I can't remember all of the articulated reasons for rejecting it, I do remember doing so explicitly (aside from the role/affiliate distinction mentioned above - if you try to use `auth.Group` for group affiliation rather than roles you either remove the ability to use it for roles or you end up with a two-headed monster in one database table). I have my doubts as to whether you could make it work using the abstract base models here, but if you can you're certainly welcome to try it and I'm sure other people would like to hear how you made it work (myself included!).
