### ISSUE TITLE
User invitation workflow

### ISSUE THREAD

**Issue by pawelad** [bennylope/django-organizations#91]
Hi,

I'm looking into the user invitation workflow and have a couple of questions - from my understanding `OrganizationUserAddForm`  creates inactive `User` and inactive `OgranizationUser` objects, and the link with `User` form is sent, which on save makes user active.
Why? Wouldn't it be *better* to just create inactive `User` model, and then create `OrganizationUser` object after user uses invitation link?

Second thing - if you add user that already has an account, he should be asked if he wants to join the organization instead of automatically being added. Don't know if that's because of basic backend implementation though.

I'll probably gonna make same changes to reflect those two situations, so if we agree on those matters I could probably do a PR after I'm done.

**Comment by bennylope** [comment]
> from my understanding `OrganizationUserAddForm` creates inactive `User` and inactive `OgranizationUser`

It creates an inactive `User` but `OrganizationUser` has no active/inactive state. It's just a link with an 'admin' checkbox.

> Wouldn't it be better to just create inactive User model, and then create OrganizationUser object after user uses invitation link?

How will you link the new user back to the organization once they register, then? The `OrganizationUser` is the link between a `User` and an `Organization` - if you just add the user you'd have to create some other way of noting what organization they were supposed to be a member of, which would be redundant. So it wouldn't be better to create the `OrganizationUser` after the invitee has used the invitation link, because you wouldn't know which `Organization` to link back to (and yes, you could encode this information in the invitation URL itself, but I'm not convinced that pushing the application state to the URL is a good idea, not the least because it poses a security risk).

> if you add user that already has an account, he should be asked if he wants to join the organization instead of automatically being added.

As user workflow goes I agree with you. As implementation goes, that's largely something that should be left to an additional or custom invitation backend I think. The solution might lie in the first quote above, that there is no active state for the `OrganizationUser`, and if this field were present then it could be made inactive until a user accepts the invitation.

I'd be amenable to something like that, but note that it should be (and certainly can be) backwards compatible. It would necessitate updating the view mixins (and probably managers) and adding a non-default invitation backend that does what you suggest, so that if anyone is using the current default backend they're not surprised by things breaking.

**Comment by pawelad** [comment]
Yeah, I was thinking about encoding it into the URL, because that would possibly take care of both things, and it makes sense in workflow sense too. We already pass `user.pk` with the URL, so adding `organization.pk` shouldn't(?) be much different.
Another `is_active` flag is also an idea, but for example you still wouldn't know which users aren't active because someone made then inactive, or because they didn't click the invitation link, which is a connected issue to me (in organization users list). Creating `OrganizationUser` after activation would take care of that...

I'll tinker around with my idea and let you know if I'll get somewhere.

**Comment by bennylope** [comment]
With regard to encoding that data in the URL, with the user ID it's encoded to get data, not create it. The state is not outsourced to the URL.

> but for example you still wouldn't know which users aren't active because someone made then inactive, or because they didn't click the invitation link, which is a connected issue to me (in organization users list)

Yep! It's the simplest way I could think of, and it doesn't handle every case. It sounds like for your use case here you'd be better off with custom organization models rather than trying to fit this onto the base `organization.models` models.

**Comment by pawelad** [comment]
OK, thanks very much for the answers. I'll close it for now, maybe reopen when I'll have more.

**Comment by pawelad** [comment]
For anyone interested, I used [Django cryptographic signing](https://docs.djangoproject.com/en/1.9/topics/signing/) as part of solution.
