### ISSUE TITLE
No password checking in 'UserRegistrationForm'

### ISSUE THREAD

**Issue by pawelad** [bennylope/django-organizations#92]
There's currently no password validation in `UserRegistrationForm` in `organizations.backends.forms` and you can go through the form with different strings in `password` and `password_confirm` fields.

And why not just extend Django's own `UserCreationForm` from `django.contrib.auth.forms` in the first place, which does exactly that?

**Comment by bennylope** [comment]
> And why not just extend Django's own UserCreationForm from django.contrib.auth.forms in the first place, which does exactly that?

Because `UserCreationForm` is a `ModelForm` for `auth.User` and the backend is user model agnostic.

It would work just as well to port the `clean_password2` validation method to `UserRegistrationForm.clean_password_confirm`.

**Comment by pawelad** [comment]
But your `UserRegistrationForm` is also `ModelForm`, same as Django's `UserCreationForm`. More then that, it even  has `auth.User` specific fields excluded - `exclude = ('is_staff', 'is_superuser', 'is_active', 'last_login', 'date_joined', 'groups', 'user_permissions')`, so I wouldn't call it `User` model agnostic.
And I think that if someone has their own `User` model, they probably will have to create their own form anyway.

Why can't it just be:
```python
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['username'] = ''

    class Meta:
        model = get_user_model()
        fields = ('username',)

```

**Comment by bennylope** [comment]
> But your UserRegistrationForm is also ModelForm, same as Django's UserCreationForm.

*Yes* it is a `ModelForm` but it is not tied to `auth.User` instead to the class specified by the user.

> More then that, it even has auth.User specific fields excluded - exclude = ('is_staff', 'is_superuser', 'is_active', 'last_login', 'date_joined', 'groups', 'user_permissions'), so I wouldn't call it User model agnostic.

Yes, it's coupled to the interface, but not that specific class.

> And I think that if someone has their own User model, they probably will have to create their own form anyway.

Indeed, I haven't used this myself in quite a long time.

In taking the time to document and file an issue I presume you want to make this better for both yourself and other people. To that end it's going to be most productive to simply point out an issue and suggest a solution and avoiding pedantry. If your `UserRegistrationForm` replacement works for other user model classes then I'm all for it.

Some things in the library that look off could use fixing because they were always wrong (e.g. the password validation above) and some things that look off (e.g. not using Django's own user creation form) were based on design decisions around custom or not-yet-ready functionality (e.g. supporting alternative user models pre-1.5).
