### ISSUE TITLE
Swappable field work-around is not working

### ISSUE THREAD

**Issue by funkybob** [bennylope/django-organizations#96]
Using Python 3.51, Django 1.8.6, django-organizations 0.6.1, django-model-utils 2.4 and 2.3.1

I still get a spurious migration to change the slug field:

```
    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(populate_from='name', unique=True, editable=False, blank=True, help_text='The name in all lowercase, suitable for URL identification', max_length=200),
        ),
    ]
```

Seems the trick of importing SlugField from your own models.py isn't working.

**Comment by bennylope** [comment]
It looks like Django's `ModelState` class builds the state based on importing the field class from its [deconstructed path name](https://github.com/django/django/blob/stable/1.8.x/django/db/migrations/state.py#L345). 

Haven't yet been able to reproduce this but that's due to unrelated errors in the test environment. Once I can do so I think extending the importing class and overriding the `deconstruct` method should solve the problem.

**Comment by bennylope** [comment]
Oy. Thanks for reporting this issue, as I'd [obviously] missed it myself. The solution was pretty simple and as long as you remove that spurious migration you shouldn't notice any more such migrations. The 0.7.0 release also removes entirely the configurable TimeStampedModel class, so if you're using that it'll be ignored in favor of a local class that won't cause migration issues.
